<?php

/**
 * @file
 * Monolog hook implementations for New Relic.
 */

/**
 * Implements hook_monolog_handler_info().
 */
function newrelic_monolog_handler_info() {
  $handlers = array();

  $handlers['newrelic'] = array(
    'label' => t('New Relic'),
    'description' => t('Logs records to New Relic using it\'s API.'),
    'group' => t('Alerts and emails'),
    'default settings' => array(
      'app_name' => variable_get('site_name', 'Drupal'),
    ),
  );

  return $handlers;
}

/**
 * Implements hook_monolog_handler_path().
 */
function newrelic_monolog_handler_path() {
  return 'handlers';
}
