<?php

/**
 * @file
 * Monolog hook implementations for Loggly.
 */

/**
 * Implements hook_monolog_handler_info().
 */
function loggly_monolog_handler_info() {
  $handlers = array();

  $handlers['loggly'] = array(
    'label' => t('Loggly'),
    'description' => t('Logs records to Loggly using the HTTP API.'),
    'group' => t('Alerts and emails'), # @TODO should be in a different group
    'default settings' => array(
      'token' => '',
    ),
  );

  return $handlers;
}

/**
 * Implements hook_monolog_handler_path().
 */
function loggly_monolog_handler_path() {
  return 'handlers';
}
